# PANDAS VISUALIZATION 
## HW 3

# Задание 1
## Склеить 3 файла по годам

In [ ]:
import pandas as pd
import numpy as np
import os

from sklearn import preprocessing

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [73]:
path = os.getcwd()
files = os.listdir(path)
files_csv = [f for f in files if f[-3:] == 'csv']
files_csv

['2015.csv', '2016.csv', '2017.csv']

In [82]:
n = len(files_csv)

In [83]:
n

3

In [139]:
df_raw = pd.DataFrame()

for i in range(n):
    data = pd.read_csv(files_csv[i])
    data['Year'] = int(files_csv[i][0:4])
    df_raw = df_raw.append(data)

df_raw = df_raw.fillna(0)

In [140]:
df_raw.head()

,Country,Dystopia Residual,Dystopia.Residual,Economy (GDP per Capita),Economy..GDP.per.Capita.,Family,Freedom,Generosity,Happiness Rank,Happiness Score,...,Health..Life.Expectancy.,Lower Confidence Interval,Region,Standard Error,Trust (Government Corruption),Trust..Government.Corruption.,Upper Confidence Interval,Whisker.high,Whisker.low,Year
0,Switzerland,2.51738,0.0,1.39651,0.0,1.34951,0.66557,0.29678,1.0,7.587,...,0.0,0.0,Western Europe,0.03411,0.41978,0.0,0.0,0.0,0.0,2015
1,Iceland,2.70201,0.0,1.30232,0.0,1.40223,0.62877,0.43630,2.0,7.561,...,0.0,0.0,Western Europe,0.04884,0.14145,0.0,0.0,0.0,0.0,2015
2,Denmark,2.49204,0.0,1.32548,0.0,1.36058,0.64938,0.34139,3.0,7.527,...,0.0,0.0,Western Europe,0.03328,0.48357,0.0,0.0,0.0,0.0,2015
3,Norway,2.46531,0.0,1.45900,0.0,1.33095,0.66973,0.34699,4.0,7.522,...,0.0,0.0,Western Europe,0.03880,0.36503,0.0,0.0,0.0,0.0,2015
4,Canada,2.45176,0.0,1.32629,0.0,1.32261,0.63297,0.45811,5.0,7.427,...,0.0,0.0,North America,0.03553,0.32957,0.0,0.0,0.0,0.0,2015

In [141]:
df_raw.tail()

,Country,Dystopia Residual,Dystopia.Residual,Economy (GDP per Capita),Economy..GDP.per.Capita.,Family,Freedom,Generosity,Happiness Rank,Happiness Score,...,Health..Life.Expectancy.,Lower Confidence Interval,Region,Standard Error,Trust (Government Corruption),Trust..Government.Corruption.,Upper Confidence Interval,Whisker.high,Whisker.low,Year
150,Rwanda,0.0,0.540061,0.0,0.368746,0.945707,0.581844,0.252756,0.0,0.0,...,0.326425,0.0,0,0.0,0.0,0.455220,0.0,3.543030,3.398970,2017
151,Syria,0.0,1.061574,0.0,0.777153,0.396103,0.081539,0.493664,0.0,0.0,...,0.500533,0.0,0,0.0,0.0,0.151347,0.0,3.663669,3.260331,2017
152,Tanzania,0.0,0.621130,0.0,0.511136,1.041990,0.390018,0.354256,0.0,0.0,...,0.364509,0.0,0,0.0,0.0,0.066035,0.0,3.461430,3.236570,2017
153,Burundi,0.0,1.683024,0.0,0.091623,0.629794,0.059901,0.204435,0.0,0.0,...,0.151611,0.0,0,0.0,0.0,0.084148,0.0,3.074690,2.735310,2017
154,Central African Republic,0.0,2.066005,0.0,0.000000,0.000000,0.270842,0.280876,0.0,0.0,...,0.018773,0.0,0,0.0,0.0,0.056565,0.0,2.864884,2.521116,2017

In [142]:
df_raw['Year'].unique()

array([2015, 2016, 2017], dtype=int64)

In [143]:
df_raw['Year'].dtype

dtype('int64')

In [144]:
for i in df_raw.columns:
    print(i)

Country
Dystopia Residual
Dystopia.Residual
Economy (GDP per Capita)
Economy..GDP.per.Capita.
Family
Freedom
Generosity
Happiness Rank
Happiness Score
Happiness.Rank
Happiness.Score
Health (Life Expectancy)
Health..Life.Expectancy.
Lower Confidence Interval
Region
Standard Error
Trust (Government Corruption)
Trust..Government.Corruption.
Upper Confidence Interval
Whisker.high
Whisker.low
Year

In [145]:
df_raw.head(1)

,Country,Dystopia Residual,Dystopia.Residual,Economy (GDP per Capita),Economy..GDP.per.Capita.,Family,Freedom,Generosity,Happiness Rank,Happiness Score,...,Health..Life.Expectancy.,Lower Confidence Interval,Region,Standard Error,Trust (Government Corruption),Trust..Government.Corruption.,Upper Confidence Interval,Whisker.high,Whisker.low,Year
0,Switzerland,2.51738,0.0,1.39651,0.0,1.34951,0.66557,0.29678,1.0,7.587,...,0.0,0.0,Western Europe,0.03411,0.41978,0.0,0.0,0.0,0.0,2015

In [147]:
df_raw['Dystopia Residual'] = df_raw['Dystopia Residual'] + df_raw['Dystopia.Residual']
df_raw['Economy (GDP per Capita)'] = df_raw['Economy (GDP per Capita)'] + df_raw['Economy..GDP.per.Capita.']
df_raw['Happiness Rank'] = df_raw['Happiness Rank'] + df_raw['Happiness.Rank']
df_raw['Happiness Score'] = df_raw['Happiness Score'] + df_raw['Happiness.Score']
df_raw['Health (Life Expectancy)'] = df_raw['Health (Life Expectancy)'] + df_raw['Health..Life.Expectancy.']
df_raw['Trust (Government Corruption)'] = df_raw['Trust (Government Corruption)'] + df_raw['Trust..Government.Corruption.']


df_raw = df_raw.rename(columns = {'Whisker.high': 'Whisker high', 'Whisker.low': 'Whisker low'})

df_raw = df_raw.drop(['Dystopia.Residual', 
                      'Economy..GDP.per.Capita.', 
                      'Happiness.Rank', 
                      'Happiness.Score', 
                      'Health..Life.Expectancy.',
                      'Trust..Government.Corruption.'], axis = 1)

In [148]:
df_raw.head(1)

,Country,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Lower Confidence Interval,Region,Standard Error,Trust (Government Corruption),Upper Confidence Interval,Whisker high,Whisker low,Year
0,Switzerland,2.51738,1.39651,1.34951,0.66557,0.29678,1.0,7.587,0.94143,0.0,Western Europe,0.03411,0.41978,0.0,0.0,0.0,2015

In [149]:
df_raw[df['Country'] == 'Denmark']

,Country,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Lower Confidence Interval,Region,Standard Error,Trust (Government Corruption),Upper Confidence Interval,Whisker high,Whisker low,Year
2,Denmark,2.492040,1.325480,1.360580,0.649380,0.34139,3.0,7.527,0.874640,0.00,Western Europe,0.03328,0.48357,0.000,0.000000,0.000000,2015
0,Denmark,2.739390,1.441780,1.163740,0.579410,0.36171,1.0,7.526,0.795040,7.46,Western Europe,0.00000,0.44453,7.592,0.000000,0.000000,2016
1,Denmark,2.313707,1.482383,1.551122,0.626007,0.35528,2.0,7.522,0.792566,0.00,0,0.00000,0.40077,0.000,7.581728,7.462272,2017

In [150]:
df_raw.describe()

,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Lower Confidence Interval,Standard Error,Trust (Government Corruption),Upper Confidence Interval,Whisker high,Whisker low,Year
count,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000,470.000000
mean,2.092717,0.927830,0.990347,0.402828,0.242241,78.829787,5.370728,0.579968,1.764545,0.016097,0.134790,1.831213,1.798107,1.733267,2015.993617
std,0.565772,0.415584,0.318707,0.150356,0.131543,45.281408,1.136998,0.240161,2.580511,0.024722,0.111313,2.670056,2.644902,2.559075,0.816907
min,0.328580,0.000000,0.000000,0.000000,0.000000,1.000000,2.693000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2015.000000
25%,1.737975,0.605292,0.793000,0.297615,0.152831,40.000000,4.509000,0.402301,0.000000,0.000000,0.059777,0.000000,0.000000,0.000000,2015.000000
50%,2.094640,0.995439,1.025665,0.418347,0.223140,79.000000,5.282500,0.630053,0.000000,0.000000,0.099502,0.000000,0.000000,0.000000,2016.000000
75%,2.455575,1.252443,1.228745,0.516850,0.315824,118.000000,6.233750,0.768298,4.325750,0.037282,0.173161,4.464500,4.556383,4.360195,2017.000000
max,3.837720,1.870766,1.610574,0.669730,0.838075,158.000000,7.587000,1.025250,7.460000,0.136930,0.551910,7.669000,7.622030,7.479556,2017.000000

In [151]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 470 entries, 0 to 154
Data columns (total 17 columns):
Country                          470 non-null object
Dystopia Residual                470 non-null float64
Economy (GDP per Capita)         470 non-null float64
Family                           470 non-null float64
Freedom                          470 non-null float64
Generosity                       470 non-null float64
Happiness Rank                   470 non-null float64
Happiness Score                  470 non-null float64
Health (Life Expectancy)         470 non-null float64
Lower Confidence Interval        470 non-null float64
Region                           470 non-null object
Standard Error                   470 non-null float64
Trust (Government Corruption)    470 non-null float64
Upper Confidence Interval        470 non-null float64
Whisker high                     470 non-null float64
Whisker low                      470 non-null float64
Year                             470 non-null int64
dtypes: float64(14), int64(1), object(2)
memory usage: 66.1+ KB

In [152]:
for i in df_raw.columns:
    print(i)

Country
Dystopia Residual
Economy (GDP per Capita)
Family
Freedom
Generosity
Happiness Rank
Happiness Score
Health (Life Expectancy)
Lower Confidence Interval
Region
Standard Error
Trust (Government Corruption)
Upper Confidence Interval
Whisker high
Whisker low
Year

In [154]:
df_raw['Region'].describe()

count     470
unique     11
top         0
freq      155
Name: Region, dtype: int64

In [155]:
df_raw['Region'].unique()

array(['Western Europe', 'North America', 'Australia and New Zealand',
       'Middle East and Northern Africa', 'Latin America and Caribbean',
       'Southeastern Asia', 'Central and Eastern Europe', 'Eastern Asia',
       'Sub-Saharan Africa', 'Southern Asia', 0], dtype=object)

# Задание 2
## Вывести информацию по топ 25 странам с наибольшим абсолютным изменением индекса счастья

# Задание 3
## Визуализировать эту информацию: Вывести распределения показателей счастья (Health, Freedom, Trust и т.д.) в том или ином виде, используя Seaborn


# Задание 4
## Построить Pairplot показателей счастья по всем странам за определённый год, выявить визуально те показатели, которые наилучшим образом между собой коррелируют (зависят друг от друга)


# Задание 5
## Построить Scatter Plotы зависимости показателей счастья от GDP, построить regression plotы на том же графике, проанализировать страны, которые лежат сильно выше/ниже линии регрессии по различным показателям